/**
 * This file contains key-value category pairs
 */
export const categories = {
  GENERAL: "GENERAL",
  HEALTH: "HEALTH",
  FOOD: "FOOD",
  GROCERY: "GROCERY",
  ENTERTAINMENT: "ENTERTAINMENT",
  RENT: "RENT",
  SUBSCRIPTIONS: "SUBSCRIPTIONS",
  TRAVEL: "TRAVEL",
  PARKING: "PARKING",
  GITF: "GIFT",
  BANK: "BANK ACCOUNT FEES",
  CLOTHING: "CLOTHING",
  CHARITABLE: "CHARITABLE CONTRIBUTIONS",
};
